### ISSUE TITLE
Minimizing history

### ISSUE THREAD

**Issue by abhith** [abyx/angular-ui-router-query-params-example#1]
As you mentioned in your [article](http://www.codelord.net/2015/11/25/query-parameters-in-ui-router-without-needless-reloading-with-example-project/) (great article though), how can we minimize the history since my current application is searching on ng-change. so if searched for car, there is 3 history ,
- /search?q=c
- /search?q=ca
- /search?q=car

**Comment by abyx** [comment]
When calling $state.go you can pass the option `location: "replace"` which should replace the current history state, instead of adding a new one

**Comment by abhith** [comment]
Thanks :)
